/**
 * © 2025 Sixsmith Games. All rights reserved.
 * This software and associated documentation files are proprietary and confidential.
 */

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaEncounterV1Json = BaseOutput & {
  title: string;
  /**
   * Narrative description of the encounter
   */
  description: string;
  /**
   * @minItems 1
   */
  characters: [
    {
      /**
       * Persistent identifier for the character
       */
      id: string;
      name: string;
      /**
       * Narrative or tactical role in the encounter
       */
      role: string;
      level: number;
      class?: string;
      hit_points: number;
      conditions?: string[];
      notes?: string;
      [k: string]: unknown;
    },
    ...{
      /**
       * Persistent identifier for the character
       */
      id: string;
      name: string;
      /**
       * Narrative or tactical role in the encounter
       */
      role: string;
      level: number;
      class?: string;
      hit_points: number;
      conditions?: string[];
      notes?: string;
      [k: string]: unknown;
    }[]
  ];
  /**
   * @minItems 0
   */
  NPCs: {
    /**
     * Canon entity identifier
     */
    entity_id: string;
    name: string;
    affiliation: string;
    motivation?: string;
    /**
     * How the NPC assists the party
     */
    support?: string;
    /**
     * Reference to stat block
     */
    stat_block?: string;
    [k: string]: unknown;
  }[];
  /**
   * @minItems 1
   */
  monsters: [
    {
      name: string;
      count: number;
      ac: number;
      hp: number;
      speed: number;
      abilities: string[];
      legendary_actions?: number;
      cr?: string;
      [k: string]: unknown;
    },
    ...{
      name: string;
      count: number;
      ac: number;
      hp: number;
      speed: number;
      abilities: string[];
      legendary_actions?: number;
      cr?: string;
      [k: string]: unknown;
    }[]
  ];
  traps: {
    name: string;
    trigger: string;
    effect: string;
    dc: number;
    disarm?: string;
    [k: string]: unknown;
  }[];
  hazards: {
    name: string;
    description: string;
    /**
     * Mechanical impact or condition
     */
    impact: string;
    mitigation?: string;
    [k: string]: unknown;
  }[];
  terrain: {
    description: string;
    features: {
      name: string;
      effect: string;
      dc?: number;
      cover?: string;
      movement?: string;
      [k: string]: unknown;
    }[];
    lighting?: "bright" | "dim" | "dark" | "magical-dark";
    elevation?: string;
    weather?: string;
    [k: string]: unknown;
  };
  /**
   * Win conditions and goals
   *
   * @minItems 1
   */
  objectives: [string, ...string[]];
  difficulty_tier: "easy" | "standard" | "deadly" | "boss";
  expected_duration_rounds: number;
  treasure: {
    type: "currency" | "item" | "boon" | "information";
    currency?: {
      gp?: number;
      sp?: number;
      cp?: number;
      [k: string]: unknown;
    };
    items?: {
      name: string;
      rarity?: string;
      description?: string;
      [k: string]: unknown;
    }[];
    boons?: string[];
    [k: string]: unknown;
  };
  event_clock: {
    summary?: string;
    /**
     * @minItems 1
     */
    phases: [
      {
        name: string;
        trigger: string;
        outcome: string;
        clock_segment?: number;
        [k: string]: unknown;
      },
      ...{
        name: string;
        trigger: string;
        outcome: string;
        clock_segment?: number;
        [k: string]: unknown;
      }[]
    ];
    [k: string]: unknown;
  };
  tactics:
    | string
    | {
        opening_moves: string;
        focus_targets?: string;
        resource_usage?: string;
        fallback_plan: string;
        [k: string]: unknown;
      };
  /**
   * @minItems 1
   */
  sources_used: [string, ...string[]];
  assumptions: string[];
  fact_check_report: {
    status: "pending" | "pass" | "fail";
    summary?: string;
    issues?: {
      description: string;
      severity: "minor" | "major" | "critical";
      resolution?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  /**
   * Schema identifier for persisted encounters
   */
  schemaVersion: string;
  [k: string]: unknown;
};

export interface BaseOutput {
  rule_base: "2024RAW" | "2014RAW";
  sources_used: string[];
  assumptions: string[];
  proposals: Proposal[];
  canon_update: string;
  [k: string]: unknown;
}
export interface Proposal {
  question: string;
  /**
   * @minItems 2
   * @maxItems 5
   */
  options:
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string];
  rule_impact: string;
  recommendation?: string;
  [k: string]: unknown;
}
