import type { LlmRequestEnvelope, LlmResponseEnvelope } from '../../shared/llm/orchestratorContracts.js';
import { MongoExecutionStore } from './executionStore.js';
import type { ExecuteOptions } from './orchestrator.js';
import { finishFreeformTicket, freeformTicketCollection, freeformTicketError, loadBoundFreeformTicket } from './freeformTickets.js';

/** No automatic attempt takeover: a lost proposal is reconciled with its
 * original durable execution, never regenerated by an elapsed lease. */
export async function executeTicketedFreeform(request: LlmRequestEnvelope, options: ExecuteOptions,
  execute: () => Promise<LlmResponseEnvelope>) {
  const records = options.freeformTickets ?? freeformTicketCollection();
  const record = await loadBoundFreeformTicket({ userId: options.userId, request, manualOutput: options.manualOutput }, records);
  if (record.status === 'accepted' && record.response) return structuredClone(record.response);
  if (record.status === 'running') {
    const execution = await (options.store ?? new MongoExecutionStore()).find(options.userId, request.operation, request.idempotencyKey);
    if (execution?.response && execution.status !== 'running') return finishFreeformTicket(record, execution.response, records);
    freeformTicketError('FREEFORM_INTAKE_PENDING');
  }
  const claim = await records.findOneAndUpdate({ _id: record._id, userId: options.userId, status: 'active' }, {
    $set: { status: 'running' },
  }, { returnDocument: 'after' });
  if (!claim) freeformTicketError('FREEFORM_INTAKE_PENDING');
  // Do not permit the compatibility adapter to replace this policy or schema.
  const response = await execute();
  return finishFreeformTicket(claim, response, records);
}
