/**
 * Generated NPC Types from schema/npc/v1-flat.json
 * DO NOT EDIT MANUALLY - Generated by scripts/generateTypes.ts
 
 *
 * © 2025 Sixsmith Games. All rights reserved.
 * This software and associated documentation files are proprietary and confidential.
 */

/**
 * Complete schema for D&D 5E NPCs with combat stats and narrative details
 */
export interface NPCSchemaV1 {
  /**
   * The NPC's canonical name
   */
  name: string;
  /**
   * Title or role (e.g., 'Knight Commander', 'Master Thief')
   */
  title?: string;
  /**
   * Alternative names, nicknames, or code names
   */
  aliases?: string[];
  /**
   * Narrative role in the story
   */
  role?: string;
  /**
   * Physical appearance, demeanor, and narrative summary
   */
  description: string;
  /**
   * Physical description
   */
  appearance?: string;
  /**
   * Personal history and backstory
   */
  background?: string;
  /**
   * Character race (e.g., 'Human', 'Elf', 'Dwarf')
   */
  race: string;
  /**
   * Creature size (e.g., 'Medium', 'Large')
   */
  size?: string;
  /**
   * Creature type (e.g., 'Humanoid', 'Undead')
   */
  creature_type?: string;
  /**
   * Creature subtype (e.g., 'Human', 'Elf')
   */
  subtype?: string;
  /**
   * Alignment (e.g., 'Lawful Good', 'Chaotic Evil')
   */
  alignment?: string;
  /**
   * Faction or organization membership
   */
  affiliation?: string;
  /**
   * Current or home location
   */
  location?: string;
  /**
   * Time period or era
   */
  era?: string;
  /**
   * Challenge Rating for combat encounters
   */
  challenge_rating?: string;
  /**
   * XP awarded for defeating this NPC
   */
  experience_points?: number;
  /**
   * Story hooks and adventure seeds
   */
  hooks?: string[];
  /**
   * Combat tactics and strategy
   */
  tactics?: string;
  /**
   * Class levels and subclasses
   */
  class_levels: {
    class: string;
    level: number;
    subclass?: string;
    notes?: string;
    [k: string]: any;
  }[];
  /**
   * The six ability scores
   */
  ability_scores: {
    str: number;
    dex: number;
    con: number;
    int: number;
    wis: number;
    cha: number;
    [k: string]: any;
  };
  /**
   * Armor Class value or list of AC values with armor types
   */
  armor_class?:
    | number
    | {
        value: number;
        type?: string;
        notes?: string;
        [k: string]: any;
      }[];
  /**
   * Hit points as integer or object with average/formula
   */
  hit_points?:
    | number
    | {
        average?: number;
        formula?: string;
        notes?: string;
        [k: string]: any;
      };
  /**
   * Hit dice formula (e.g., '8d8+16')
   */
  hit_dice?: string;
  /**
   * Proficiency bonus value
   */
  proficiency_bonus: number | string;
  /**
   * Movement speeds by type
   */
  speed?: {
    walk?: string;
    fly?: string;
    swim?: string;
    climb?: string;
    burrow?: string;
    hover?: string;
  };
  /**
   * Saving throw proficiencies with bonuses
   */
  saving_throws?: {
    name: string;
    value: string;
    notes?: string;
    [k: string]: any;
  }[];
  /**
   * Skill proficiencies with bonuses
   */
  skill_proficiencies?: {
    name: string;
    value: string;
    notes?: string;
    [k: string]: any;
  }[];
  /**
   * Special senses (darkvision, blindsight, etc.)
   */
  senses?: string[];
  /**
   * Passive Perception score
   */
  passive_perception?: number;
  /**
   * Languages known
   */
  languages?: string[];
  /**
   * Damage types resisted
   */
  damage_resistances?: string[];
  /**
   * Damage types immune to
   */
  damage_immunities?: string[];
  /**
   * Damage types vulnerable to
   */
  damage_vulnerabilities?: string[];
  /**
   * Conditions immune to
   */
  condition_immunities?: string[];
  /**
   * Special abilities and traits
   */
  abilities?: {
    name: string;
    description: string;
    uses?: string;
    recharge?: string;
    notes?: string;
    [k: string]: any;
  }[];
  /**
   * Additional traits not listed elsewhere
   */
  additional_traits?: {
    name: string;
    description: string;
    uses?: string;
    recharge?: string;
    notes?: string;
    [k: string]: any;
  }[];
  /**
   * Equipment carried
   */
  equipment?: string[];
  /**
   * Relationships with other entities
   */
  relationships?: {
    entity: string;
    relationship: string;
    notes?: string;
    [k: string]: any;
  }[];
  /**
   * Personality traits, ideals, bonds, and flaws
   */
  personality: {
    traits: string[];
    ideals: string[];
    bonds: string[];
    flaws: string[];
    [k: string]: any;
  };
  /**
   * Character motivations and goals
   */
  motivations: string[];
  /**
   * Spellcasting information
   */
  spellcasting?: {
    type?: string;
    ability?: string;
    save_dc?: number;
    attack_bonus?: number;
    notes?: string;
    spell_slots?: {
      [k: string]: number;
    };
    prepared_spells?: {
      [k: string]: string[];
    };
    innate_spells?: {
      [k: string]: string[];
    };
    known_spells?: string[];
    [k: string]: any;
  };
  /**
   * Actions available in combat
   */
  actions?: {
    name: string;
    description: string;
    uses?: string;
    recharge?: string;
    notes?: string;
    [k: string]: any;
  }[];
  /**
   * Bonus actions available
   */
  bonus_actions?: {
    name: string;
    description: string;
    uses?: string;
    recharge?: string;
    notes?: string;
    [k: string]: any;
  }[];
  /**
   * Reactions available
   */
  reactions?: {
    name: string;
    description: string;
    uses?: string;
    recharge?: string;
    notes?: string;
    [k: string]: any;
  }[];
  /**
   * Legendary actions
   */
  legendary_actions?: {
    summary?: string;
    options?: {
      name: string;
      description: string;
      uses?: string;
      recharge?: string;
      notes?: string;
      [k: string]: any;
    }[];
    [k: string]: any;
  };
  /**
   * Mythic actions
   */
  mythic_actions?: {
    summary?: string;
    options?: {
      name: string;
      description: string;
      uses?: string;
      recharge?: string;
      notes?: string;
      [k: string]: any;
    }[];
    [k: string]: any;
  };
  /**
   * Actions available in the NPC's lair
   */
  lair_actions?: string[];
  /**
   * Regional effects around the NPC's lair
   */
  regional_effects?: string[];
  /**
   * Additional notes and GM guidance
   */
  notes?: string[];
  /**
   * Source books and references
   */
  sources?: string[];
  /**
   * Raw stat block data captured from the generator
   */
  stat_block?: {
    [k: string]: any;
  };
  /**
   * Rules version being used
   */
  rule_base: '2024RAW' | '2014RAW';
  /**
   * Canon sources referenced during generation
   */
  sources_used: string[];
  /**
   * Assumptions made during generation
   */
  assumptions: string[];
  /**
   * Open questions requiring user input
   */
  proposals: {
    question: string;
    /**
     * @minItems 2
     * @maxItems 5
     */
    options:
      | [string, string]
      | [string, string, string]
      | [string, string, string, string]
      | [string, string, string, string, string];
    rule_impact: string;
    recommendation?: string;
    [k: string]: any;
  }[];
  /**
   * Summary of canon changes or additions
   */
  canon_update: string;
  [k: string]: any;
}
