/**
 * Type Generation Script
 *
 * Generates TypeScript interfaces from JSON schemas.
 * Run with: npx tsx scripts/generateTypes.ts
 */

import { compileFromFile } from 'json-schema-to-typescript';
import { writeFile, mkdir } from 'fs/promises';
import { join, dirname } from 'path';
import { existsSync } from 'fs';

interface SchemaConfig {
  schemaPath: string;
  outputPath: string;
  bannerComment?: string;
}

const SCHEMAS: SchemaConfig[] = [
  {
    schemaPath: 'schema/npc/v1-flat.json',
    outputPath: 'client/src/types/npc/generated.ts',
    bannerComment: '/**\n * Generated NPC Types from schema/npc/v1-flat.json\n * DO NOT EDIT MANUALLY - Generated by scripts/generateTypes.ts\n */',
  },
  // TODO: Create flat encounter schema without external refs
  // {
  //   schemaPath: 'schema/encounter/v1.json',
  //   outputPath: 'client/src/types/encounter/generated.ts',
  //   bannerComment: '/**\n * Generated Encounter Types from schema/encounter/v1.json\n * DO NOT EDIT MANUALLY - Generated by scripts/generateTypes.ts\n */',
  // },
];

async function ensureDirectory(filePath: string): Promise<void> {
  const dir = dirname(filePath);
  if (!existsSync(dir)) {
    await mkdir(dir, { recursive: true });
  }
}

async function generateTypes(): Promise<void> {
  console.log('🔧 Generating TypeScript types from JSON schemas...\n');

  for (const config of SCHEMAS) {
    try {
      const schemaPath = join(process.cwd(), config.schemaPath);
      const outputPath = join(process.cwd(), config.outputPath);

      console.log(`📄 Processing: ${config.schemaPath}`);

      // Generate TypeScript from schema
      const ts = await compileFromFile(schemaPath, {
        bannerComment: config.bannerComment || '',
        style: {
          bracketSpacing: true,
          printWidth: 120,
          semi: true,
          singleQuote: true,
          tabWidth: 2,
          trailingComma: 'es5',
        },
        unknownAny: false,
        cwd: process.cwd(),
      });

      // Ensure output directory exists
      await ensureDirectory(outputPath);

      // Write generated types
      await writeFile(outputPath, ts, 'utf-8');

      console.log(`✅ Generated: ${config.outputPath}\n`);
    } catch (error) {
      console.error(`❌ Error generating types for ${config.schemaPath}:`);
      console.error(error);
      process.exit(1);
    }
  }

  console.log('✅ Type generation complete!');
}

// Run generation
generateTypes().catch((error) => {
  console.error('❌ Type generation failed:');
  console.error(error);
  process.exit(1);
});
